spring:
  application:
    name: activity-service
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: fitnessactivity
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


  #Eureka
eureka:
#   instance:
#    hostname: localhost
#    preferIpAddress: false
   client:
     service-url:
       defaultZone: http://localhost:8761/eureka/
   fetch-registry: true
   register-with-eureka: true

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking
#How message is routed from exchange to queue

server:
  port: 8082
#  address: 127:0:0:1
