spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness_user_db
    username: saurabhs
    password: saurabhs
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
   client:
     service-url:
       defaultZone: http://localhost:8761/eureka/
   fetch-registry: true
   register-with-eureka: true
#   instance:
#     hostname: localhost
#     preferIpAddress: false

server:
  port: 8081
#  address: 127:0:0:1